export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";

export const ADD_SUGGESTIONS = "SHOW_SUGGESTIONS";
export const SHOW_SUGGESTIONS = "SHOW_SUGGESTIONS";
export const LOAD_CONTENT = "LOAD_CONTENT";
export const HIDE_SUGGETIONS = "HIDE_SUGGETIONS";
export const CHANGE_SUGGESTION = "CHANGE_SUGGESTION";
export const FIRE_LAST = "FIRE_LAST";
